version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    environment:
      OTEL_EXPORTER_CLICKHOUSE_ENDPOINT: ${OTEL_EXPORTER_CLICKHOUSE_ENDPOINT}
      OTEL_EXPORTER_CLICKHOUSE_DATABASE: ${OTEL_EXPORTER_CLICKHOUSE_DATABASE}
      OTEL_EXPORTER_CLICKHOUSE_USERNAME: ${OTEL_EXPORTER_CLICKHOUSE_USERNAME}
      OTEL_EXPORTER_CLICKHOUSE_PASSWORD: ${OTEL_EXPORTER_CLICKHOUSE_PASSWORD}
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
  
  meal-order:
    build: ./microservices/online-meal-order
    environment:
      - OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "${MEAL_ORDER_PORT}:3000"
    env_file:
    - .env
    restart: always

  meal-restaurant:
    build: ./microservices/online-meal-restaurant-owner
    environment:
      - OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "${MEAL_RESTAURANT_PORT}:3000" 
    env_file:
    - .env
    restart: always

  image-server:
    build: ./microservices/image-server
    environment:
      - OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "${IMAGE_PORT}:3000" 
    env_file:
    - .env
    restart: always

  delivery-service1:
    build: ./microservices/delivery-service
    environment:
      - OTLP_ENDPOINT=http://otel-collector:4317
      - SERVICE_NAME=delivery-service1
    ports:
      - "${DELIVERY_PORT1}:3000"
    env_file:
    - .env
    restart: always

  delivery-service2:
    build: ./microservices/delivery-service
    environment:
      - OTLP_ENDPOINT=http://otel-collector:4317
      - SERVICE_NAME=delivery-service2
    ports:
      - "${DELIVERY_PORT2}:3000" 
    env_file:
    - .env
    restart: always

  delivery-service3:
    build: ./microservices/delivery-service
    environment:
      - OTLP_ENDPOINT=http://otel-collector:4317
      - SERVICE_NAME=delivery-service3
    ports:
      - "${DELIVERY_PORT3}:3000" 
    env_file:
    - .env
    restart: always

  delivery-service4:
    build: ./microservices/delivery-service
    environment:
      - OTLP_ENDPOINT=http://otel-collector:4317
      - SERVICE_NAME=delivery-service4
    ports:
      - "${DELIVERY_PORT4}:3000" 
    env_file:
    - .env
    restart: always
  tester:
    build: ./microservices/tester
    env_file:
    - .env
    restart: always
  



