receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: "0.0.0.0:4351"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [logging, otlp]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [logging, otlp]